### ISSUE TITLE
google cloud platform 安装失败

### ISSUE THREAD

**Issue by nemo2018** [wulabing/h5ai_onekey_install-lnp-#1]
下面是log
cat h5ai.log
[OK]  当前系统为 Debian 9 
[OK]  当前用户是root用户，进入安装流程 
 请选择安装内容 
1. h5ai
2. SSL
3. h5ai+SSL
Hit:1 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://security.debian.org stretch/updates InRelease
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease
Hit:6 http://deb.debian.org/debian stretch-backports InRelease
Hit:7 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Hit:8 http://deb.debian.org/debian stretch Release
Reading package lists...
Building dependency tree...
Reading state information...
35 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists...
Building dependency tree...
Reading state information...
bc is already the newest version (1.06.95-9+b3).
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
unzip is already the newest version (6.0-21).
wget is already the newest version (1.18-5+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
域名dns解析IP：35.229.162.xxx
本机IP: 10.140.0.5
[Error]  域名dns解析IP 与 本机IP 不匹配 是否继续安装？（y/n）
 继续安装 
deb http://packages.dotdeb.org jessie all
deb-src http://packages.dotdeb.org jessie all
OK
[OK]  导入 GPG 秘钥成功 
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
Ign:3 http://deb.debian.org/debian stretch InRelease
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease
Hit:6 http://deb.debian.org/debian stretch-backports InRelease
Hit:7 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Hit:8 http://deb.debian.org/debian stretch Release
Get:10 http://packages.dotdeb.org jessie InRelease [9,872 B]
Get:11 http://packages.dotdeb.org jessie/all Sources [47.8 kB]
Get:12 http://packages.dotdeb.org jessie/all amd64 Packages [236 kB]
Fetched 293 kB in 2s (110 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx : Depends: nginx-full (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed or
                  nginx-light (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed or
                  nginx-extras (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed
         Depends: nginx-full (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed or
                  nginx-light (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed or
                  nginx-extras (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed
[Error]  nginx 安装失败

**Comment by nemo2018** [comment]
还是谷歌的换ubuntu17，得到类似的错误。

**Comment by wulabing** [comment]
您好，已收到相关反馈，我会在近日进行处理（几天之内吧，最近事情多）。感谢您的理解

**Comment by nemo2018** [comment]
当然理解。多谢！

**Comment by wulabing** [comment]
你这台机器是同时用了我的 V2ray 和 h5ai 脚本么。

**Comment by nemo2018** [comment]
又跑了一遍，纯系统，最下面错误提示的上面一点多了一行。

> it:7 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Hit:8 http://deb.debian.org/debian stretch Release
Get:10 http://packages.dotdeb.org jessie InRelease [9,872 B]
Get:11 http://packages.dotdeb.org jessie/all Sources [47.8 kB]
Get:12 http://packages.dotdeb.org jessie/all amd64 Packages [236 kB]
Fetched 293 kB in 2s (118 kB/s)
Reading package lists...

>**WARNING: apt does not have a stable CLI interface. Use with caution in scripts.**

>Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 nginx : Depends: nginx-full (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed or
                  nginx-light (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed or
                  nginx-extras (>= 1.12.2-1~dotdeb+8.1) but it is not going to be installed
         Depends: nginx-full (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed or
                  nginx-light (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed or
                  nginx-extras (< 1.12.2-1~dotdeb+8.1.1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
[Error]  nginx 安装失败

**Comment by nemo2018** [comment]
好奇怪，我并没有画删除线，是触发了github的格式化机制了。看图。
![image](https://user-images.githubusercontent.com/37334053/37693745-b2fe4a46-2cfc-11e8-87e0-897111620979.png)

**Comment by wulabing** [comment]
一开始写脚本默认是安装最新版nginx。
刚才把新版本的deb源去掉了。重建一个环境用新脚本试一下

**Comment by nemo2018** [comment]
可以了。谢谢
还问下。
1， 如果在你的v2ray里面装h5,是不是开始的时候选1h5ai就行了，因为已经装过SSL了？
2，如果是用了wiki的为了配合CF修改配置的方法，对h5ai安装，有什么需要改的么？
非常感谢！

**Comment by wulabing** [comment]
1.按道理来说，是的（不过我自己并没验证过）
2.如果在1的基础上，那应该不需要更改配置，直接套就能用

**Comment by nemo2018** [comment]
h5ai目录应该是 /home/wwwroot/我的域名吧？

**Comment by wulabing** [comment]
在readme里面有写

**Comment by nemo2018** [comment]
就是看了readme找了好久，最后在另外一个地方找到了才问的你啊。

**Comment by wulabing** [comment]
是readme写错了，:)
