### ISSUE TITLE
这不是issue，本脚本+隔壁V2Ray_ws-tls_bash_onekey 部署在一个机器上方法

### ISSUE THREAD

**Issue by nemo2018** [wulabing/h5ai_onekey_install-lnp-#2]
亲自测试可行，为了让站点更具隐蔽性而且还可以多发挥一点vps的热量，两个脚本可以合并无干扰运行。
1，先装v2ray那个 [脚本](https://github.com/wulabing/V2Ray_ws-tls_bash_onekey)
2，再装本脚本，注意开始的时候选1，别选2和3，因为在第一步已经申请证书了。
3，进目录/etc/nginx/conf.d，打开里面的h5hai.conf放一边
4，同目录下进入编辑模式打开v2ray.conf。建议拷贝出来用熟悉的编辑器，事后再拷贝回去。
5，修改的内容：
a，拷贝h5hai.conf里面root 一行和index一行，**覆盖**v2ray.conf里面对应的两行。
b，拷贝h5hai.conf里面location那一段。粘贴到v2ray.conf里面已经有的location一段的后面。拷贝整段的意思是一直到大括号完了的内容。还有粘贴过去的时候注意两段location之间是**没有分号**的。
6，重启nginx服务即可

至此域名访问是h5ai，同时v2ray照样运行。更可以支持cf嵌套，唯一需要修改的就是SSL 要使用full 或full(strick)
多谢这两个脚本，认为是见到的最好的脚本。
enjoy!

**Comment by wulabing** [comment]
你这么一弄。我想在下一次大版本更新的时候干脆直接把 H5AI和V2RAY结合在一起好了，本来H5AI就可以做为页面伪装，正好也可以存一些东西，H5AI作为一个网盘界面简约而且优雅。

**Comment by nemo2018** [comment]
好主意

**Comment by nemo2018** [comment]
稍微折腾一下不麻烦，正好顺边学一下玩一下Linux。

**Comment by wulabing** [comment]
哈哈哈  那你来push吧。我来merge

**Comment by nemo2018** [comment]
我还没能力写bash脚本。只是小打小闹改一下配置文件 :)

**Comment by wulabing** [comment]
我慢慢改。小改动，就是容易改出错。
